const recipes=window.RECIPES;
let selected=new Set(JSON.parse(localStorage.getItem("selectedMeals")||"[]")), buy=new Set(JSON.parse(localStorage.getItem("buyItems")||"[]")),filter="All",shopFilter="All";
const cats=["All","Chicken","Beef","Fish","Pork","Lamb","Vegetarian","Quick ≤ 30 mins"], grid=document.querySelector("#grid"),filters=document.querySelector("#filters"),search=document.querySelector("#search");
function toast(s){const t=document.querySelector("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
function rf(){filters.innerHTML=cats.map(c=>`<button class="chip ${c===filter?"active":""}" data-c="${c}">${c}</button>`).join("");filters.querySelectorAll("button").forEach(b=>b.onclick=()=>{filter=b.dataset.c;rf();renderMeals()})}
function match(r){const q=search.value.trim().toLowerCase(),f=filter==="All"||r.category===filter||(filter.startsWith("Quick")&&r.minutes<=30);return f&&(!q||(r.name+" "+r.style+" "+r.description).toLowerCase().includes(q))}
function renderMeals(){grid.innerHTML=recipes.filter(match).map(r=>`<article class="card ${selected.has(r.id)?"selected":""}" data-id="${r.id}"><div class="photo"><span class="dish">${r.style}</span><span class="select">${selected.has(r.id)?"✓":""}</span></div><div class="body"><div class="name">${r.name}</div><div class="desc">${r.description}</div><div class="meta"><span>◷ ${r.time}</span><span>🍴 ${r.category}</span></div></div></article>`).join("");grid.querySelectorAll(".card").forEach(c=>c.onclick=()=>{selected.has(c.dataset.id)?selected.delete(c.dataset.id):selected.add(c.dataset.id);localStorage.setItem("selectedMeals",JSON.stringify([...selected]));renderMeals()});document.querySelector("#count").textContent=`${selected.size} meal${selected.size===1?"":"s"} selected`}
function ingredientRows(){let rows=[];recipes.filter(r=>selected.has(r.id)).forEach(r=>r.ingredients.forEach(i=>{let key=r.id+"|"+i.order;rows.push({...i,key,meal:r.name})}));return rows}
function renderShopping(){let rows=ingredientRows(), needed=rows.filter(x=>buy.has(x.key)).length;document.querySelector("#shopFilters").innerHTML=[["All",rows.length],["To buy",needed],["Not needed",rows.length-needed]].map(([x,n])=>`<button class="${shopFilter===x?"active":""}" data-f="${x}">${x} (${n})</button>`).join("");document.querySelectorAll("#shopFilters button").forEach(b=>b.onclick=()=>{shopFilter=b.dataset.f;renderShopping()});if(shopFilter==="To buy")rows=rows.filter(x=>buy.has(x.key));if(shopFilter==="Not needed")rows=rows.filter(x=>!buy.has(x.key));let groups={};rows.forEach(x=>(groups[x.category]??=[]).push(x));let order=["Meat & Fish","Dairy & Eggs","Fruit & Vegetables","Bakery","Store Cupboard"];document.querySelector("#shoppingList").innerHTML=order.filter(g=>groups[g]?.length).map(g=>`<section class="shopgroup"><h2>${g}</h2><div class="shopitems">${groups[g].map(x=>`<label class="shoprow"><input type="checkbox" data-key="${x.key}" ${buy.has(x.key)?"checked":""}><span>${x.item}<span class="sources">${x.meal}</span></span><span class="amount">${x.amount??""}</span></label>`).join("")}</div></section>`).join("")||`<div class="shopgroup"><p>No ingredients to show. Select meals first.</p></div>`;document.querySelectorAll(".shoprow input").forEach(c=>c.onchange=()=>{c.checked?buy.add(c.dataset.key):buy.delete(c.dataset.key);localStorage.setItem("buyItems",JSON.stringify([...buy]));renderShopping()});document.querySelector("#buyCount").textContent=`${needed} item${needed===1?"":"s"} selected`}
function showPage(p){const meals=p==="meals";document.querySelector("#mealsPage").classList.toggle("hidden",!meals);document.querySelector("#shoppingPage").classList.toggle("hidden",meals);document.querySelector("#selectionBar").classList.toggle("hidden",!meals);document.querySelector("#shopBar").classList.toggle("hidden",meals);document.querySelector("#mealsNav").classList.toggle("active",meals);document.querySelector("#shoppingNav").classList.toggle("active",!meals);if(!meals)renderShopping();window.scrollTo(0,0)}
function keepList(){const rows=ingredientRows().filter(x=>buy.has(x.key));return rows.map(x=>`${x.item}${x.amount?" — "+x.amount:""}`).join("\n")}
search.oninput=renderMeals;document.querySelector("#create").onclick=()=>{if(!selected.size)return toast("Select at least one meal first");showPage("shopping")};document.querySelector("#mealsNav").onclick=()=>showPage("meals");document.querySelector("#shoppingNav").onclick=()=>showPage("shopping");document.querySelector("#cookNav").onclick=()=>toast("Cook screen is the next build");
document.querySelector("#clearBuy").onclick=()=>{buy.clear();localStorage.setItem("buyItems","[]");renderShopping()};
document.querySelector("#prepareKeep").onclick=()=>{const s=keepList();if(!s)return toast("Tick the ingredients you need first");document.querySelector("#keepText").value=s;document.querySelector("#keepBox").classList.remove("hidden");document.querySelector("#keepBox").scrollIntoView({behavior:"smooth"})};
document.querySelector("#copyKeep").onclick=async()=>{await navigator.clipboard.writeText(document.querySelector("#keepText").value);toast("Shopping list copied")};
document.querySelector("#shareKeep").onclick=async()=>{const text=document.querySelector("#keepText").value;if(navigator.share)try{await navigator.share({title:"Shopping list",text})}catch(e){}else{await navigator.clipboard.writeText(text);toast("Copied — paste into Google Keep")}};
rf();renderMeals();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});