const recipes=window.RECIPES;
const SUPABASE_URL="https://afyfshqbbsbeqfvosqkn.supabase.co";
const SUPABASE_KEY="sb_publishable_zFpXaY2jrFGm_uRw2C-EPA_Me31uwpp";
let selected=new Set(JSON.parse(localStorage.getItem("selectedMeals")||"[]")),buy=new Set(JSON.parse(localStorage.getItem("buyItems")||"[]"));
let filter="All",sourceFilter="All",ratingFilter="All",cookedFilter="All",shopFilter="All",prefs={},editingRecipeId=null;
let householdKey=localStorage.getItem("mealPlannerHouseholdKey")||"";
const cats=["All","Chicken","Beef","Fish","Pork","Lamb","Vegetarian","Quick ≤ 30 mins"],grid=document.querySelector("#grid"),filters=document.querySelector("#filters"),search=document.querySelector("#search");
const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(s){const t=document.querySelector("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1900)}
function defaultPref(r){return{recipe_id:r.id,source:r.id==="beef-fajita-enchiladas"?"J":"AI",cooked:false,rating:null,comments:""}}
function pref(r){return prefs[r.id]||defaultPref(r)}
async function api(path,opts={}){const headers={apikey:SUPABASE_KEY,"Content-Type":"application/json",Prefer:"return=representation",...(householdKey?{"x-household-key":householdKey}:{}),...(opts.headers||{})};const res=await fetch(SUPABASE_URL+"/rest/v1/"+path,{...opts,headers});if(!res.ok){const detail=await res.text();throw new Error("Supabase "+res.status+": "+detail)}const text=await res.text();return text?JSON.parse(text):[]}
async function loadPrefs(){try{const rows=await api("meal_preferences?select=recipe_id,source,cooked,rating,comments,updated_at");prefs=Object.fromEntries(rows.map(x=>[x.recipe_id,x]));const missing=recipes.filter(r=>!prefs[r.id]).map(defaultPref);if(missing.length){const made=await api("meal_preferences?on_conflict=recipe_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(missing)});made.forEach(x=>prefs[x.recipe_id]=x)}document.body.classList.remove("syncing");document.querySelector("#syncState").textContent="Synced";renderMeals();if(!document.querySelector("#cookPage").classList.contains("hidden"))renderRecipe()}catch(e){console.error(e);document.querySelector("#syncState").textContent="Offline";toast("Shared ratings unavailable — check connection")}}
async function savePref(id,changes){const previous={...pref(recipes.find(r=>r.id===id))};const current={...previous,...changes,recipe_id:id};prefs[id]=current;renderMeals();try{const rows=await api("meal_preferences?recipe_id=eq."+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify(changes)});if(!rows[0])throw new Error("No record was updated");prefs[id]=rows[0];document.querySelector("#syncState").textContent="Synced";return true}catch(e){console.error(e);prefs[id]=previous;renderMeals();document.querySelector("#syncState").textContent="Not synced";toast("Could not sync change");return false}}
function rf(){filters.innerHTML=cats.map(c=>`<button class="chip ${c===filter?"active":""}" data-c="${c}">${c}</button>`).join("");filters.querySelectorAll("button").forEach(b=>b.onclick=()=>{filter=b.dataset.c;rf();renderMeals()})}
function ratingMatch(p){if(ratingFilter==="All")return true;if(ratingFilter==="5")return p.rating===5;if(ratingFilter==="4+")return p.rating>=4;if(ratingFilter==="3-")return p.rating!=null&&p.rating<=3;if(ratingFilter==="Unrated")return p.rating==null;return true}
function match(r){const q=search.value.trim().toLowerCase(),p=pref(r),f=filter==="All"||r.category===filter||(filter.startsWith("Quick")&&r.minutes<=30),sf=sourceFilter==="All"||p.source===sourceFilter,cf=cookedFilter==="All"||(cookedFilter==="Cooked"&&p.cooked)||(cookedFilter==="Not cooked"&&!p.cooked);return f&&sf&&cf&&ratingMatch(p)&&(!q||(r.name+" "+r.style+" "+r.description).toLowerCase().includes(q))}
function stars(n){return n?`<span class="cardstars" aria-label="${n} stars">${"★".repeat(n)}</span>`:""}
function renderMeals(){grid.innerHTML=recipes.filter(match).map(r=>{const p=pref(r);return`<article class="card ${selected.has(r.id)?"selected":""}" data-id="${r.id}"><div class="photo" style="background-image:url('${r.id}.webp')"><span class="dish">${esc(r.style)}</span><span class="select">${selected.has(r.id)?"✓":""}</span></div><div class="body"><div class="name">${esc(r.name)}</div><div class="desc">${esc(r.description)}</div><div class="meta"><span>◷ ${esc(r.time)}</span><span>🍴 ${esc(r.category)}</span></div><div class="reviewmeta"><span class="sourcebadge">${esc(p.source||"–")}</span>${stars(p.rating)}${p.cooked?'<span title="Cooked before">✓</span>':''}${p.comments?'<span title="Has comments">▰</span>':''}<button class="reviewbtn" data-review="${r.id}" aria-label="Review ${esc(r.name)}">•••</button></div></div></article>`}).join("");grid.querySelectorAll(".card").forEach(c=>c.onclick=e=>{if(e.target.closest(".reviewbtn"))return;selected.has(c.dataset.id)?selected.delete(c.dataset.id):selected.add(c.dataset.id);localStorage.setItem("selectedMeals",JSON.stringify([...selected]));renderMeals()});grid.querySelectorAll(".reviewbtn").forEach(b=>b.onclick=e=>{e.stopPropagation();openReview(b.dataset.review)});document.querySelector("#count").textContent=`${selected.size} meal${selected.size===1?"":"s"} selected`;document.querySelector("#visibleCount").textContent=`${recipes.filter(match).length} shown`}
function setupAdvancedFilters(){const sf=document.querySelector("#sourceFilter"),rf=document.querySelector("#ratingFilter"),cf=document.querySelector("#cookedFilter");sf.onchange=()=>{sourceFilter=sf.value;renderMeals()};rf.onchange=()=>{ratingFilter=rf.value;renderMeals()};cf.onchange=()=>{cookedFilter=cf.value;renderMeals()}}
function openReview(id){editingRecipeId=id;const r=recipes.find(x=>x.id===id),p=pref(r);document.querySelector("#reviewTitle").textContent=r.name;document.querySelector("#reviewSource").value=p.source||"AI";document.querySelector("#reviewCooked").checked=!!p.cooked;document.querySelector("#reviewComments").value=p.comments||"";document.querySelectorAll("#reviewStars button").forEach(b=>b.classList.toggle("active",Number(b.dataset.rating)<=Number(p.rating||0)));document.querySelector("#reviewRating").value=p.rating??"";document.querySelector("#reviewModal").classList.remove("hidden")}
function closeReview(){document.querySelector("#reviewModal").classList.add("hidden");editingRecipeId=null}
document.querySelectorAll("#reviewStars button").forEach(b=>b.onclick=()=>{document.querySelector("#reviewRating").value=b.dataset.rating;document.querySelectorAll("#reviewStars button").forEach(x=>x.classList.toggle("active",Number(x.dataset.rating)<=Number(b.dataset.rating)))});
document.querySelector("#clearRating").onclick=()=>{document.querySelector("#reviewRating").value="";document.querySelectorAll("#reviewStars button").forEach(x=>x.classList.remove("active"))};
document.querySelector("#cancelReview").onclick=closeReview;document.querySelector("#reviewModal").onclick=e=>{if(e.target.id==="reviewModal")closeReview()};
document.querySelector("#saveReview").onclick=async()=>{if(!editingRecipeId)return;const id=editingRecipeId,rating=document.querySelector("#reviewRating").value;const ok=await savePref(id,{source:document.querySelector("#reviewSource").value,cooked:document.querySelector("#reviewCooked").checked,rating:rating?Number(rating):null,comments:document.querySelector("#reviewComments").value.trim()});if(ok){closeReview();if(currentCook===id)renderRecipe();toast("Saved & synced")}};
function ingredientRows(){let rows=[];recipes.filter(r=>selected.has(r.id)).forEach(r=>r.ingredients.forEach(i=>{let key=r.id+"|"+i.order;rows.push({...i,key,meal:r.name})}));return rows}
function renderShopping(){let rows=ingredientRows(),needed=rows.filter(x=>buy.has(x.key)).length;document.querySelector("#shopFilters").innerHTML=[["All",rows.length],["To buy",needed],["Not needed",rows.length-needed]].map(([x,n])=>`<button class="${shopFilter===x?"active":""}" data-f="${x}">${x} (${n})</button>`).join("");document.querySelectorAll("#shopFilters button").forEach(b=>b.onclick=()=>{shopFilter=b.dataset.f;renderShopping()});if(shopFilter==="To buy")rows=rows.filter(x=>buy.has(x.key));if(shopFilter==="Not needed")rows=rows.filter(x=>!buy.has(x.key));let groups={};rows.forEach(x=>(groups[x.category]??=[]).push(x));let order=["Meat & Fish","Dairy & Eggs","Fruit & Vegetables","Bakery","Store Cupboard"];document.querySelector("#shoppingList").innerHTML=order.filter(g=>groups[g]?.length).map(g=>`<section class="shopgroup"><h2>${g}</h2><div class="shopitems">${groups[g].map(x=>`<label class="shoprow"><input type="checkbox" data-key="${x.key}" ${buy.has(x.key)?"checked":""}><span>${esc(x.item)}<span class="sources">${esc(x.meal)}</span></span><span class="amount">${esc(x.amount??"")}</span></label>`).join("")}</div></section>`).join("")||`<div class="shopgroup"><p>No ingredients to show. Select meals first.</p></div>`;document.querySelectorAll(".shoprow input").forEach(c=>c.onchange=()=>{c.checked?buy.add(c.dataset.key):buy.delete(c.dataset.key);localStorage.setItem("buyItems",JSON.stringify([...buy]));renderShopping()});document.querySelector("#buyCount").textContent=`${needed} item${needed===1?"":"s"} selected`}
function showPage(p){const isMeals=p==="meals",isShop=p==="shopping",isCook=p==="cook";document.querySelector("#mealsPage").classList.toggle("hidden",!isMeals);document.querySelector("#shoppingPage").classList.toggle("hidden",!isShop);document.querySelector("#cookPage").classList.toggle("hidden",!isCook);document.querySelector("#selectionBar").classList.toggle("hidden",!isMeals);document.querySelector("#shopBar").classList.toggle("hidden",!isShop || groceryMode!=="combined");["mealsNav","shoppingNav","cookNav"].forEach(id=>document.querySelector("#"+id).classList.remove("active"));document.querySelector("#"+p+"Nav").classList.add("active");if(isShop)renderShopping();if(isCook)renderCookPicker();window.scrollTo(0,0)}
function keepList(){return ingredientRows().filter(x=>buy.has(x.key)).map(x=>`${x.item}${x.amount?" — "+x.amount:""}`).join("\n")}
search.oninput=renderMeals;document.querySelector("#create").onclick=()=>{if(!selected.size)return toast("Select at least one meal first");showPage("shopping")};document.querySelector("#mealsNav").onclick=()=>showPage("meals");document.querySelector("#shoppingNav").onclick=()=>showPage("shopping");document.querySelector("#cookNav").onclick=()=>showPage("cook");document.querySelector("#clearBuy").onclick=()=>{buy.clear();localStorage.setItem("buyItems","[]");renderShopping()};document.querySelector("#prepareKeep").onclick=()=>{const s=keepList();if(!s)return toast("Select something for the shopping list first");document.querySelector("#keepText").value=s;document.querySelector("#keepBox").classList.remove("hidden");document.querySelector("#keepBox").scrollIntoView({behavior:"smooth"})};document.querySelector("#copyKeep").onclick=async()=>{await navigator.clipboard.writeText(document.querySelector("#keepText").value);toast("Shopping list copied")};document.querySelector("#shareKeep").onclick=async()=>{const text=document.querySelector("#keepText").value;if(navigator.share)try{await navigator.share({title:"Shopping list",text})}catch(e){}else{await navigator.clipboard.writeText(text);toast("Copied — paste into Google Keep")}};
let currentCook=localStorage.getItem("currentCook")||"",wakeLock=null;function selectedRecipes(){return recipes.filter(r=>selected.has(r.id))}
function renderCookPicker(){const rs=selectedRecipes(),sel=document.querySelector("#cookMealSelect"),empty=document.querySelector("#cookEmpty"),view=document.querySelector("#recipeView");if(!rs.length){sel.innerHTML="<option>No meals selected</option>";empty.classList.remove("hidden");view.classList.add("hidden");return}empty.classList.add("hidden");view.classList.remove("hidden");if(!rs.some(r=>r.id===currentCook))currentCook=rs[0].id;sel.innerHTML=rs.map(r=>`<option value="${r.id}" ${r.id===currentCook?"selected":""}>${esc(r.name)}</option>`).join("");sel.onchange=()=>{currentCook=sel.value;localStorage.setItem("currentCook",currentCook);renderRecipe()};renderRecipe()}
function renderRecipe(){const r=recipes.find(x=>x.id===currentCook);if(!r)return;const p=pref(r);document.querySelector("#cookTitle").textContent=r.name;document.querySelector("#cookStyle").textContent=r.style;document.querySelector(".recipehero").style.backgroundImage=`linear-gradient(0deg,rgba(10,30,23,.72),rgba(10,30,23,.05) 70%),url('${r.id}.webp')`;document.querySelector("#cookTime").textContent="◷ "+r.time;document.querySelector("#cookCategory").textContent=r.category;document.querySelector("#cookReviewSummary").innerHTML=`<span class="sourcebadge">${esc(p.source||"–")}</span> ${p.rating?"★".repeat(p.rating):"Unrated"}${p.cooked?" · ✓ Cooked":""}${p.comments?" · ▰ Notes":""}`;document.querySelector("#editCookReview").onclick=()=>openReview(r.id);const checked=new Set(JSON.parse(localStorage.getItem("cookChecked:"+r.id)||"[]"));document.querySelector("#cookIngredients").innerHTML=r.ingredients.map(i=>`<label class="ingredientline"><input type="checkbox" data-o="${i.order}" ${checked.has(String(i.order))?"checked":""}><span>${esc(i.item)}</span><span class="amount">${esc(i.amount??"")}</span></label>`).join("");document.querySelectorAll("#cookIngredients input").forEach(c=>c.onchange=()=>{c.checked?checked.add(c.dataset.o):checked.delete(c.dataset.o);localStorage.setItem("cookChecked:"+r.id,JSON.stringify([...checked]))});document.querySelector("#cookMethod").innerHTML=r.method.map((s,n)=>`<div class="methodstep"><span class="stepnum">${n+1}</span><span>${esc(s.text)}</span></div>`).join("")}
function cookTab(which){const ing=which==="ingredients";document.querySelector("#cookIngredients").classList.toggle("hidden",!ing);document.querySelector("#cookMethod").classList.toggle("hidden",ing);document.querySelector("#ingredientsTab").classList.toggle("active",ing);document.querySelector("#methodTab").classList.toggle("active",!ing)}document.querySelector("#ingredientsTab").onclick=()=>cookTab("ingredients");document.querySelector("#methodTab").onclick=()=>cookTab("method");document.querySelector("#wakeButton").onclick=async()=>{const b=document.querySelector("#wakeButton"),s=document.querySelector("#wakeStatus");if(wakeLock){try{await wakeLock.release()}catch(e){}wakeLock=null;b.classList.remove("active");b.textContent="Start cooking · keep screen on";s.textContent="";return}if(!("wakeLock"in navigator)){s.textContent="This browser does not support keeping the screen awake automatically.";return}try{wakeLock=await navigator.wakeLock.request("screen");b.classList.add("active");b.textContent="Cooking mode on · allow screen to sleep";s.textContent="Screen will stay awake while Meal Planner remains visible.";wakeLock.addEventListener("release",()=>{wakeLock=null;b.classList.remove("active");b.textContent="Start cooking · keep screen on"})}catch(e){s.textContent="Screen-awake permission was not available. Your normal screen timeout will apply."}};document.addEventListener("visibilitychange",async()=>{if(document.visibilityState==="visible"&&document.querySelector("#wakeButton").classList.contains("active")&&!wakeLock&&"wakeLock"in navigator)try{wakeLock=await navigator.wakeLock.request("screen")}catch(e){}});
function showAccess(){document.querySelector("#accessModal").classList.remove("hidden");document.querySelector("#householdCode").value=householdKey;setTimeout(()=>document.querySelector("#householdCode").focus(),50)}
document.querySelector("#saveHouseholdCode").onclick=async()=>{const v=document.querySelector("#householdCode").value.trim();if(!v)return toast("Enter the household access code");householdKey=v;localStorage.setItem("mealPlannerHouseholdKey",v);document.querySelector("#accessModal").classList.add("hidden");document.querySelector("#syncState").textContent="Syncing…";await loadPrefs()};
document.querySelector("#changeAccess").onclick=showAccess;
rf();setupAdvancedFilters();renderMeals();if(householdKey)loadPrefs();else{document.querySelector("#syncState").textContent="Access needed";showAccess()}if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});

/* v5.3 shared regular groceries */
let groceryItems=[],groceryMode="ingredients";
const groceryOrder=["Fruit & Vegetables","Meat & Fish","Dairy & Eggs","Bakery","Chilled & Frozen","Store Cupboard","Household","Toiletries","Other"];
function normaliseItem(s){return String(s||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9 ]/g," ").replace(/\b(fresh|small|medium|large|lean|low fat|low-fat)\b/g," ").replace(/\s+/g," ").trim().replace(/ies$/,"y").replace(/oes$/,"o").replace(/s$/,"")}
function groceryCategory(name){const n=name.toLowerCase();if(/toilet|tooth|shampoo|soap|deodorant|conditioner/.test(n))return"Toiletries";if(/washing|kitchen roll|bin bag|clean|foil|cling|dishwasher|laundry/.test(n))return"Household";if(/frozen|ice cream/.test(n))return"Chilled & Frozen";if(/bread|roll|wrap|pitta|bagel|croissant/.test(n))return"Bakery";if(/milk|butter|egg|cheese|cheddar|yogh|cream/.test(n))return"Dairy & Eggs";if(/chicken|beef|pork|bacon|ham|lamb|salmon|cod|fish|sausage|mince/.test(n))return"Meat & Fish";if(/apple|banana|berry|berries|carrot|potato|onion|tomato|pepper|salad|lettuce|cucumber|lemon|lime|garlic|ginger|herb|coriander|parsley|fruit|veg/.test(n))return"Fruit & Vegetables";return"Store Cupboard"}
async function loadGroceries(){if(!householdKey)return;try{groceryItems=await api("grocery_items?select=id,name,normalized_name,category,selected,updated_at&order=category.asc,name.asc");renderGroceries();renderCombined()}catch(e){console.error(e);toast("Regular groceries unavailable")}}
function visibleGroceries(){const q=(document.querySelector("#grocerySearch")?.value||"").trim().toLowerCase();return groceryItems.filter(x=>!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q))}
function renderGroceries(){const host=document.querySelector("#groceryList");if(!host)return;const rows=visibleGroceries(),groups={};rows.forEach(x=>(groups[x.category]??=[]).push(x));host.innerHTML=groceryOrder.filter(g=>groups[g]?.length).map(g=>`<section class="shopgroup"><h2>${esc(g)}</h2><div class="shopitems">${groups[g].sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<label class="shoprow groceryrow"><input type="checkbox" data-gid="${x.id}" ${x.selected?"checked":""}><span>${esc(x.name)}</span><button type="button" class="groceryedit" data-edit-gid="${x.id}" aria-label="Edit ${esc(x.name)}">•••</button></label>`).join("")}</div></section>`).join("")||`<div class="groceryempty">${groceryItems.length?"No matching items.":"No regular groceries yet. Type an item above and tap Add."}</div>`;host.querySelectorAll("input[data-gid]").forEach(c=>c.onchange=async()=>{const id=Number(c.dataset.gid),item=groceryItems.find(x=>x.id===id),before=item.selected;item.selected=c.checked;renderCombined();try{await api("grocery_items?id=eq."+id,{method:"PATCH",body:JSON.stringify({selected:c.checked})})}catch(e){item.selected=before;c.checked=before;toast("Could not sync grocery change")}});host.querySelectorAll("[data-edit-gid]").forEach(b=>b.onclick=e=>{e.preventDefault();editGrocery(Number(b.dataset.editGid))})}
async function addGrocery(){const input=document.querySelector("#grocerySearch"),name=input.value.trim();if(!name)return toast("Type an item to add");const norm=normaliseItem(name);const existing=groceryItems.find(x=>normaliseItem(x.name)===norm||x.normalized_name===norm);if(existing){if(!existing.selected){existing.selected=true;try{await api("grocery_items?id=eq."+existing.id,{method:"PATCH",body:JSON.stringify({selected:true})})}catch(e){existing.selected=false;return toast("Could not sync grocery change")}}input.value="";renderGroceries();renderCombined();return toast(existing.name+" already exists — selected")};const row={name,normalized_name:norm,category:groceryCategory(name),selected:true};try{const made=await api("grocery_items",{method:"POST",body:JSON.stringify(row)});if(made[0])groceryItems.push(made[0]);input.value="";renderGroceries();renderCombined();toast("Added & selected")}catch(e){console.error(e);toast("Could not add item")}}
async function editGrocery(id){const item=groceryItems.find(x=>x.id===id);if(!item)return;const name=prompt("Rename item (leave blank to delete):",item.name);if(name===null)return;if(!name.trim()){if(!confirm(`Remove ${item.name} from the regular list?`))return;try{await api("grocery_items?id=eq."+id,{method:"DELETE"});groceryItems=groceryItems.filter(x=>x.id!==id);renderGroceries();renderCombined();toast("Item removed")}catch(e){toast("Could not remove item")}return}const clean=name.trim(),norm=normaliseItem(clean);if(groceryItems.some(x=>x.id!==id&&(x.normalized_name===norm||normaliseItem(x.name)===norm)))return toast("That item is already in the list");try{const rows=await api("grocery_items?id=eq."+id,{method:"PATCH",body:JSON.stringify({name:clean,normalized_name:norm,category:groceryCategory(clean)})});if(rows[0])Object.assign(item,rows[0]);renderGroceries();renderCombined();toast("Item updated")}catch(e){toast("Could not update item")}}
async function setVisibleGroceries(value){const ids=visibleGroceries().map(x=>x.id);if(!ids.length)return;const previous=groceryItems.map(x=>[x.id,x.selected]);groceryItems.forEach(x=>{if(ids.includes(x.id))x.selected=value});renderGroceries();renderCombined();try{await api("grocery_items?id=in.("+ids.join(",")+")",{method:"PATCH",body:JSON.stringify({selected:value})});toast(value?"Selected all shown":"Deselected all shown")}catch(e){previous.forEach(([id,v])=>{const x=groceryItems.find(y=>y.id===id);if(x)x.selected=v});renderGroceries();renderCombined();toast("Could not sync selection")}}
function combinedRows(){const result=[],seen=new Map();ingredientRows().filter(x=>buy.has(x.key)).forEach(x=>{const norm=normaliseItem(x.item),row={name:x.item,amount:x.amount||"",category:x.category||"Other",source:"Meals"};result.push(row);if(norm)seen.set(norm,row)});groceryItems.filter(x=>x.selected).forEach(x=>{const norm=normaliseItem(x.name);if(seen.has(norm)){const row=seen.get(norm);row.source="Meals + regular"}else{const row={name:x.name,amount:"",category:x.category||"Other",source:"Regular"};result.push(row);seen.set(norm,row)}});return result}
function renderCombined(){const host=document.querySelector("#combinedList");if(!host)return;const rows=combinedRows(),groups={};rows.forEach(x=>(groups[x.category]??=[]).push(x));host.innerHTML=groceryOrder.filter(g=>groups[g]?.length).map(g=>`<section class="shopgroup"><h2>${esc(g)}</h2><div class="shopitems">${groups[g].sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<div class="shoprow"><span>✓</span><span>${esc(x.name)}<span class="duplicate-note">${esc(x.source)}</span></span><span class="amount">${esc(x.amount)}</span></div>`).join("")}</div></section>`).join("")||`<div class="groceryempty">Nothing selected yet.</div>`}
function setShopMode(mode){groceryMode=mode;document.querySelectorAll("#shopMode button").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));document.querySelector("#ingredientShopping").classList.toggle("hidden",mode!=="ingredients");document.querySelector("#groceryShopping").classList.toggle("hidden",mode!=="groceries");document.querySelector("#combinedShopping").classList.toggle("hidden",mode!=="combined");document.querySelector("#shopBar").classList.toggle("hidden",mode!=="combined" || document.querySelector("#shoppingPage").classList.contains("hidden"));if(mode!=="combined")document.querySelector("#keepBox").classList.add("hidden");if(mode==="groceries")renderGroceries();if(mode==="combined")renderCombined()}
const renderShoppingV52=renderShopping;renderShopping=function(){renderShoppingV52();renderCombined()};
keepList=function(){return combinedRows().map(x=>`${x.name}${x.amount?" — "+x.amount:""}`).join("\n")};
document.querySelectorAll("#shopMode button").forEach(b=>b.onclick=()=>setShopMode(b.dataset.mode));document.querySelector("#grocerySearch").oninput=renderGroceries;document.querySelector("#grocerySearch").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addGrocery()}};document.querySelector("#addGrocery").onclick=addGrocery;document.querySelector("#selectVisibleGroceries").onclick=()=>setVisibleGroceries(true);document.querySelector("#deselectVisibleGroceries").onclick=()=>setVisibleGroceries(false);
const loadPrefsV52=loadPrefs;loadPrefs=async function(){await loadPrefsV52();await loadGroceries()};
if(householdKey)loadGroceries();
// v5.3 count and wording polish
const renderShoppingV53=renderShopping;renderShopping=function(){renderShoppingV53();const n=combinedRows().length;document.querySelector("#buyCount").textContent=`${n} item${n===1?"":"s"} selected`};
