-- Meal Planner v5.3: shared regular grocery master list
create table if not exists public.grocery_items (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text not null unique,
  category text not null default 'Other',
  selected boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.grocery_items enable row level security;

grant select, insert, update, delete on table public.grocery_items to anon;
grant usage, select on sequence public.grocery_items_id_seq to anon;

drop policy if exists "Meal Planner groceries read" on public.grocery_items;
drop policy if exists "Meal Planner groceries insert" on public.grocery_items;
drop policy if exists "Meal Planner groceries update" on public.grocery_items;
drop policy if exists "Meal Planner groceries delete" on public.grocery_items;

create policy "Meal Planner groceries read" on public.grocery_items
for select to anon using (public.meal_planner_access_ok());
create policy "Meal Planner groceries insert" on public.grocery_items
for insert to anon with check (public.meal_planner_access_ok());
create policy "Meal Planner groceries update" on public.grocery_items
for update to anon using (public.meal_planner_access_ok()) with check (public.meal_planner_access_ok());
create policy "Meal Planner groceries delete" on public.grocery_items
for delete to anon using (public.meal_planner_access_ok());

-- A useful starter list. ON CONFLICT makes this safe to run again.
insert into public.grocery_items (name, normalized_name, category) values
('Apples','apples','Fruit & Vegetables'),('Bananas','bananas','Fruit & Vegetables'),('Blueberries','blueberries','Fruit & Vegetables'),('Carrots','carrots','Fruit & Vegetables'),('Potatoes','potatoes','Fruit & Vegetables'),('Onions','onions','Fruit & Vegetables'),('Salad leaves','salad leaves','Fruit & Vegetables'),('Tomatoes','tomatoes','Fruit & Vegetables'),
('Milk','milk','Dairy & Eggs'),('Butter','butter','Dairy & Eggs'),('Eggs','eggs','Dairy & Eggs'),('Cheddar','cheddar','Dairy & Eggs'),('Yoghurt','yoghurt','Dairy & Eggs'),
('Bread','bread','Bakery'),('Wraps','wraps','Bakery'),
('Chicken breasts','chicken breasts','Meat & Fish'),('Bacon','bacon','Meat & Fish'),('Ham','ham','Meat & Fish'),
('Frozen peas','frozen peas','Chilled & Frozen'),('Frozen chips','frozen chips','Chilled & Frozen'),
('Baked beans','baked beans','Store Cupboard'),('Tinned tomatoes','tinned tomatoes','Store Cupboard'),('Pasta','pasta','Store Cupboard'),('Rice','rice','Store Cupboard'),('Tea bags','tea bags','Store Cupboard'),('Coffee','coffee','Store Cupboard'),('Sugar','sugar','Store Cupboard'),('Cooking oil','cooking oil','Store Cupboard'),
('Kitchen roll','kitchen roll','Household'),('Washing-up liquid','washing up liquid','Household'),('Washing powder','washing powder','Household'),('Bin bags','bin bags','Household'),
('Toilet roll','toilet roll','Toiletries'),('Toothpaste','toothpaste','Toiletries'),('Shampoo','shampoo','Toiletries')
on conflict (normalized_name) do nothing;
