-- Meal Planner v5.4: editable, shared grocery departments
create table if not exists public.grocery_departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);

alter table public.grocery_departments enable row level security;
grant select, insert, update, delete on table public.grocery_departments to anon;
grant usage, select on sequence public.grocery_departments_id_seq to anon;

drop policy if exists "Meal Planner departments read" on public.grocery_departments;
drop policy if exists "Meal Planner departments insert" on public.grocery_departments;
drop policy if exists "Meal Planner departments update" on public.grocery_departments;
drop policy if exists "Meal Planner departments delete" on public.grocery_departments;
create policy "Meal Planner departments read" on public.grocery_departments for select to anon using (public.meal_planner_access_ok());
create policy "Meal Planner departments insert" on public.grocery_departments for insert to anon with check (public.meal_planner_access_ok());
create policy "Meal Planner departments update" on public.grocery_departments for update to anon using (public.meal_planner_access_ok()) with check (public.meal_planner_access_ok());
create policy "Meal Planner departments delete" on public.grocery_departments for delete to anon using (public.meal_planner_access_ok());

insert into public.grocery_departments (name, sort_order) values
('Fruit & Vegetables',10),('Meat & Fish',20),('Dairy & Eggs',30),('Bakery',40),('Chilled & Frozen',50),('Store Cupboard',60),('Soft Drinks',70),('Alcohol',80),('Household',90),('Toiletries',100),('Other',110)
on conflict (name) do nothing;
